package widok;

/**
 *
 * @author Mati
 */
public class StartFrame extends javax.swing.JFrame {

    public StartFrame(GameFrame gm) {
        initComponents();
        this.gm=gm;
    }

    private StartFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3x3", "5x5", "10x10", "15x15", "30x30" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "5", "7", "10" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setText("Start Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Size");

        jLabel2.setText("Colors");

        jLabel3.setText("JIGSAW PUZZLE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(jLabel2)))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        selectFromJComboBox();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void selectFromJComboBox() {
        if(jComboBox1.getSelectedItem().equals("3x3") && jComboBox2.getSelectedItem().equals("3")) {
            startGame(3, 3, 3, 0, this);
        } else if(jComboBox1.getSelectedItem().equals("3x3") && jComboBox2.getSelectedItem().equals("5")){
            startGame(3, 3, 5, 0, this);
        } else if(jComboBox1.getSelectedItem().equals("3x3") && jComboBox2.getSelectedItem().equals("7")){
            startGame(3, 3, 7, 0, this);
        } else if(jComboBox1.getSelectedItem().equals("3x3") && jComboBox2.getSelectedItem().equals("10")){
            startGame(3, 3, 10, 0, this);
        } else if(jComboBox1.getSelectedItem().equals("5x5") && jComboBox2.getSelectedItem().equals("3")){
            startGame(5, 5, 3, 100, this);
        } else if(jComboBox1.getSelectedItem().equals("5x5") && jComboBox2.getSelectedItem().equals("5")){
            startGame(5, 5, 5, 100, this);
        } else if(jComboBox1.getSelectedItem().equals("5x5") && jComboBox2.getSelectedItem().equals("7")){
            startGame(5, 5, 7, 100, this);
        } else if(jComboBox1.getSelectedItem().equals("5x5") && jComboBox2.getSelectedItem().equals("10")){
            startGame(5, 5, 10, 100, this);
        } else if(jComboBox1.getSelectedItem().equals("10x10") && jComboBox2.getSelectedItem().equals("3")){
            startGame(10, 10, 3, 60, this);
        } else if(jComboBox1.getSelectedItem().equals("10x10") && jComboBox2.getSelectedItem().equals("5")){
            startGame(10, 10, 5, 60, this);
        } else if(jComboBox1.getSelectedItem().equals("10x10") && jComboBox2.getSelectedItem().equals("7")){
            startGame(10, 10, 7, 60, this);
        } else if(jComboBox1.getSelectedItem().equals("10x10") && jComboBox2.getSelectedItem().equals("10")){
            startGame(10, 10, 10, 60, this);
        } else if(jComboBox1.getSelectedItem().equals("15x15") && jComboBox2.getSelectedItem().equals("3")){
            startGame(15, 15, 3, 20, this);
        } else if(jComboBox1.getSelectedItem().equals("15x15") && jComboBox2.getSelectedItem().equals("5")){
            startGame(15, 15, 5, 20, this);
        } else if(jComboBox1.getSelectedItem().equals("15x15") && jComboBox2.getSelectedItem().equals("7")){
            startGame(15, 15, 7, 20, this);
        } else if(jComboBox1.getSelectedItem().equals("15x15") && jComboBox2.getSelectedItem().equals("10")){
            startGame(15, 15, 10, 20, this);
        } else if(jComboBox1.getSelectedItem().equals("30x30") && jComboBox2.getSelectedItem().equals("3")){
            startGame(30, 30, 3, 5, this);
        } else if(jComboBox1.getSelectedItem().equals("30x30") && jComboBox2.getSelectedItem().equals("5")){
            startGame(30, 30, 5, 5, this);
        } else if(jComboBox1.getSelectedItem().equals("30x30") && jComboBox2.getSelectedItem().equals("7")){
            startGame(30, 30, 7, 5, this);
        } else if(jComboBox1.getSelectedItem().equals("30x30") && jComboBox2.getSelectedItem().equals("10")){
            startGame(30, 30, 10, 5, this);
        }
            
    }

    private void startGame(int l, int c, int nc, int time, StartFrame s) {
        if (time == 0) {
            gm.startGame(l, c, nc, s);
            gm.setTime(0);
            gm.setScore(true);   
        } else {
            gm.startGame(l, c, nc, s);
            gm.setTime(time);
            gm.setScore(true);
        }
        this.setVisible(false);
        gm.setVisible(true);
    }
            
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartFrame().setVisible(true);
            }
        });
    }

    GameFrame gm = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
